// Fixtures statiques pour getListData (data simulée des listes de widgets).
// La cle 'daily-actions' n'est PAS incluse ici car elle est resolue
// dynamiquement dans getListData via getDailyActionsData().
export const listDataFixtures: { [key: string]: any[] } = {
  'stock-status': [
    {
      id: '1',
      title: 'Pelle CAT 320',
      status: 'En rupture',
      priority: 'high',
      stock: 0,
      minStock: 2,
      category: 'Équipements lourds',
      supplier: 'CAT Maroc',
      lastOrder: '2024-01-15',
      nextDelivery: '2024-01-25',
      value: 850000,
      location: 'Entrepôt Casablanca',
      supplierPhone: '+212 5 22 34 56 78',
      supplierEmail: 'contact@catmaroc.ma',
      orderQuantity: 3,
      estimatedCost: 2550000,
      notes: 'Urgent - Projet autoroute Tanger-Casablanca'
    },
    {
      id: '2',
      title: 'Chargeur JCB 3CX',
      status: 'Stock faible',
      priority: 'medium',
      stock: 1,
      minStock: 3,
      category: 'Équipements lourds',
      supplier: 'JCB Maroc',
      lastOrder: '2024-01-10',
      nextDelivery: '2024-01-30',
      value: 420000,
      location: 'Entrepôt Rabat',
      supplierPhone: '+212 5 37 21 43 65',
      supplierEmail: 'contact@jcbmaroc.ma',
      orderQuantity: 2,
      estimatedCost: 840000,
      notes: 'Stock critique - Commande recommandée'
    },
    {
      id: '3',
      title: 'Bulldozer D6',
      status: 'Disponible',
      priority: 'low',
      stock: 4,
      minStock: 2,
      category: 'Équipements lourds',
      supplier: 'CAT Maroc',
      lastOrder: '2024-01-05',
      nextDelivery: null,
      value: 650000,
      location: 'Entrepôt Marrakech',
      supplierPhone: '+212 5 24 38 91 23',
      supplierEmail: 'contact@catmaroc.ma',
      orderQuantity: 0,
      estimatedCost: 0,
      notes: 'Stock suffisant - Pas de commande nécessaire'
    },
    {
      id: '4',
      title: 'Excavatrice Komatsu',
      status: 'Stock faible',
      priority: 'medium',
      stock: 1,
      minStock: 2,
      category: 'Équipements lourds',
      supplier: 'Komatsu Maroc',
      lastOrder: '2024-01-12',
      nextDelivery: '2024-01-28',
      value: 580000,
      location: 'Entrepôt Fès',
      supplierPhone: '+212 5 35 67 89 12',
      supplierEmail: 'contact@komatsumaroc.ma',
      orderQuantity: 1,
      estimatedCost: 580000,
      notes: 'Livraison en cours - Surveiller le stock'
    },
    {
      id: '5',
      title: 'Camion benne 20T',
      status: 'Disponible',
      priority: 'low',
      stock: 6,
      minStock: 3,
      category: 'Transport',
      supplier: 'Mercedes Maroc',
      lastOrder: '2024-01-08',
      nextDelivery: null,
      value: 280000,
      location: 'Entrepôt Agadir',
      supplierPhone: '+212 5 28 82 45 67',
      supplierEmail: 'contact@mercedesmaroc.ma',
      orderQuantity: 0,
      estimatedCost: 0,
      notes: 'Stock optimal - Pas d\'action requise'
    }
  ],
  'pending-orders': [
    {
      id: '1',
      title: 'Commande CAT 320',
      status: 'En préparation',
      priority: 'high',
      supplier: 'CAT Maroc',
      orderDate: '2024-01-15',
      expectedDelivery: '2024-01-25',
      value: 2550000,
      progress: 75,
      notes: 'Livraison prévue à Casablanca'
    },
    {
      id: '2',
      title: 'Commande JCB 3CX',
      status: 'En transit',
      priority: 'medium',
      supplier: 'JCB Maroc',
      orderDate: '2024-01-10',
      expectedDelivery: '2024-01-30',
      value: 1260000,
      progress: 90,
      notes: 'En route depuis Tanger'
    },
    {
      id: '3',
      title: 'Commande pièces détachées',
      status: 'En attente',
      priority: 'low',
      supplier: 'Parts Plus',
      orderDate: '2024-01-20',
      expectedDelivery: '2024-02-05',
      value: 45000,
      progress: 25,
      notes: 'Pièces pour maintenance préventive'
    }
  ],

  'stock-action': [
    {
      id: '1',
      title: 'Bulldozer D6',
      status: 'Stock dormant',
      daysInStock: 92,
      lastContact: '2024-01-05',
      price: 650000,
      recommendedAction: 'Baisser le prix de 3%',
      estimatedTimeToSell: 15,
      category: 'Équipements lourds',
      location: 'Entrepôt Marrakech',
      priority: 'high'
    },
    {
      id: '2',
      title: 'Chargeur JCB 3CX',
      status: 'Stock actif',
      daysInStock: 15,
      lastContact: '2024-01-20',
      price: 420000,
      recommendedAction: 'Booster la visibilité',
      estimatedTimeToSell: 8,
      category: 'Équipements lourds',
      location: 'Entrepôt Rabat',
      priority: 'medium'
    },
    {
      id: '3',
      title: 'Excavatrice Komatsu',
      status: 'Stock dormant',
      daysInStock: 45,
      lastContact: '2024-01-10',
      price: 580000,
      recommendedAction: 'Proposer livraison gratuite',
      estimatedTimeToSell: 12,
      category: 'Équipements lourds',
      location: 'Entrepôt Fès',
      priority: 'high'
    }
  ],
  'prospection-assistant': [
    {
      id: '1',
      name: 'Fatima Zahra',
      company: 'Construction Atlas',
      stage: 'Qualification',
      probability: 85,
      value: 850000,
      lastContact: '2024-01-22',
      nextAction: 'Envoyer devis personnalisé',
      equipment: 'CAT 950GC',
      visits: 3,
      priority: 'high',
      notes: 'Prospect très intéressé, a consulté 3 fois cette semaine'
    },
    {
      id: '2',
      name: 'Ahmed Benali',
      company: 'BTP Maroc',
      stage: 'Négociation',
      probability: 70,
      value: 1200000,
      lastContact: '2024-01-20',
      nextAction: 'Relancer par WhatsApp',
      equipment: 'JCB 3CX',
      visits: 2,
      priority: 'medium',
      notes: 'En attente de validation budgétaire'
    },
    {
      id: '3',
      name: 'Karim El Fassi',
      company: 'Infrastructure Plus',
      stage: 'Prospection',
      probability: 40,
      value: 650000,
      lastContact: '2024-01-18',
      nextAction: 'Proposer essai machine',
      equipment: 'Bulldozer D6',
      visits: 1,
      priority: 'low',
      notes: 'Premier contact, à développer'
    }
  ],
  'daily-priority-actions': [
    {
      id: '1',
      title: 'Relancer Ahmed Benali (prospect chaud)',
      description: 'Prospect qui a consulté votre 950GC 3 fois cette semaine',
      priority: 'high',
      category: 'prospection',
      impact: 'Élevé - 85% de probabilité de conversion',
      estimatedTime: '15 min',
      icon: '👤',
      action: 'Envoyer message WhatsApp personnalisé'
    },
    {
      id: '2',
      title: 'Réduire le prix du CAT 320D (-2.5%)',
      description: 'Machine en stock depuis 92 jours sans contact',
      priority: 'medium',
      category: 'pricing',
      impact: 'Moyen - Augmentation de 40% des vues attendues',
      estimatedTime: '5 min',
      icon: '💰',
      action: 'Mettre à jour le prix et booster la visibilité'
    },
    {
      id: '3',
      title: 'Publier une annonce pour compacteur',
      description: 'Forte demande détectée à Casablanca cette semaine',
      priority: 'medium',
      category: 'marketing',
      impact: 'Moyen - 15-20 prospects qualifiés attendus',
      estimatedTime: '20 min',
      icon: '📢',
      action: 'Créer annonce optimisée SEO'
    }
  ],
  'sales-evolution': [
    { id: '1', month: 'Jan 2024', sales: 1250000, target: 1000000, growth: 25,   sectorAverage: 18, trend: 'up',   metric: 'revenue' },
    { id: '2', month: 'Fév 2024', sales: 1350000, target: 1100000, growth: 22.7, sectorAverage: 15, trend: 'up',   metric: 'revenue' },
    { id: '3', month: 'Mar 2024', sales: 1420000, target: 1200000, growth: 18.3, sectorAverage: 12, trend: 'up',   metric: 'revenue' },
    { id: '4', month: 'Avr 2024', sales: 1380000, target: 1300000, growth: -2.8, sectorAverage: 8,  trend: 'down', metric: 'revenue' },
    { id: '5', month: 'Mai 2024', sales: 1520000, target: 1400000, growth: 10.1, sectorAverage: 14, trend: 'up',   metric: 'revenue' },
    { id: '6', month: 'Juin 2024',sales: 1680000, target: 1500000, growth: 10.5, sectorAverage: 16, trend: 'up',   metric: 'revenue' }
  ],
  'sales-pipeline': [
    {
      id: '1',
      title: 'Projet Autoroute Tanger-Casablanca',
      stage: 'Qualification',
      priority: 'high',
      value: 8500000,
      company: 'Société Nationale des Autoroutes',
      contact: 'Ahmed Benali',
      phone: '+212 5 22 34 56 78',
      email: 'a.benali@sna.ma',
      lastContact: '2024-01-20',
      nextAction: 'Appel de suivi',
      probability: 75,
      expectedClose: '2024-02-15',
      notes: 'Projet majeur - Besoin en équipements lourds'
    },
    {
      id: '2',
      title: 'Construction Centre Commercial Rabat',
      stage: 'Proposition',
      priority: 'medium',
      value: 3200000,
      company: 'Groupe Alliances',
      contact: 'Fatima Zahra',
      phone: '+212 5 37 21 43 65',
      email: 'f.zahra@alliances.ma',
      lastContact: '2024-01-18',
      nextAction: 'Envoi devis',
      probability: 60,
      expectedClose: '2024-02-28',
      notes: 'Location d\'équipements pour 6 mois'
    },
    {
      id: '3',
      title: 'Extension Port Tanger Med',
      stage: 'Négociation',
      priority: 'high',
      value: 12500000,
      company: 'Tanger Med Port Authority',
      contact: 'Mohammed Tazi',
      phone: '+212 5 39 94 12 34',
      email: 'm.tazi@tmsa.ma',
      lastContact: '2024-01-22',
      nextAction: 'Réunion technique',
      probability: 85,
      expectedClose: '2024-03-10',
      notes: 'Projet stratégique - Vente et location'
    },
    {
      id: '4',
      title: 'Mine de Phosphate Khouribga',
      stage: 'Qualification',
      priority: 'medium',
      value: 6800000,
      company: 'Office Chérifien des Phosphates',
      contact: 'Karim El Fassi',
      phone: '+212 5 23 45 67 89',
      email: 'k.elfassi@ocp.ma',
      lastContact: '2024-01-15',
      nextAction: 'Visite site',
      probability: 70,
      expectedClose: '2024-03-20',
      notes: 'Renouvellement équipements miniers'
    },
    {
      id: '5',
      title: 'Projet Éolien Tarfaya',
      stage: 'Prospection',
      priority: 'low',
      value: 4500000,
      company: 'Nareva Holding',
      contact: 'Sara Bennani',
      phone: '+212 5 28 82 45 67',
      email: 's.bennani@nareva.ma',
      lastContact: '2024-01-10',
      nextAction: 'Premier contact',
      probability: 30,
      expectedClose: '2024-04-15',
      notes: 'Nouveau prospect - Équipements de transport'
    }
  ],
  'inventory-status': [
    {
      id: '1',
      title: 'Pelle CAT 320',
      status: 'Stock dormant',
      priority: 'high',
      stock: 2,
      minStock: 2,
      category: 'Équipements lourds',
      supplier: 'CAT Maroc',
      lastOrder: '2024-01-15',
      nextDelivery: '2024-01-25',
      value: 850000,
      location: 'Entrepôt Casablanca',
      supplierPhone: '+212 5 22 34 56 78',
      supplierEmail: 'contact@catmaroc.ma',
      orderQuantity: 3,
      estimatedCost: 2550000,
      notes: 'Urgent - Projet autoroute Tanger-Casablanca',
      dormantDays: 95,
      visibilityRate: 15,
      averageSalesTime: 45,
      clickCount: 3,
      lastContact: '2024-01-10',
      priceReduction: 0,
      premiumBoost: false,
      salesHistory: [1200000, 980000, 850000, 720000, 650000],
      marketDemand: 'Moyenne',
      competitorPrice: 920000,
      seasonalTrend: 'Baisse'
    },
    {
      id: '2',
      title: 'Chargeur JCB 3CX',
      status: 'Faible visibilité',
      priority: 'medium',
      stock: 1,
      minStock: 3,
      category: 'Équipements lourds',
      supplier: 'JCB Maroc',
      lastOrder: '2024-01-10',
      nextDelivery: '2024-01-30',
      value: 420000,
      location: 'Entrepôt Rabat',
      dormantDays: 45,
      visibilityRate: 25,
      averageSalesTime: 38,
      clickCount: 8,
      lastContact: '2024-01-15',
      priceReduction: 0,
      premiumBoost: false,
      salesHistory: [480000, 450000, 420000, 400000, 380000],
      marketDemand: 'Élevée',
      competitorPrice: 450000,
      seasonalTrend: 'Stable'
    },
    {
      id: '3',
      title: 'Bulldozer D6',
      status: 'Stock dormant',
      priority: 'high',
      stock: 4,
      minStock: 2,
      category: 'Équipements lourds',
      supplier: 'CAT Maroc',
      lastOrder: '2024-01-05',
      nextDelivery: null,
      value: 650000,
      location: 'Entrepôt Marrakech',
      dormantDays: 120,
      visibilityRate: 8,
      averageSalesTime: 67,
      clickCount: 1,
      lastContact: '2024-01-02',
      priceReduction: 0,
      premiumBoost: false,
      salesHistory: [750000, 720000, 680000, 650000, 620000],
      marketDemand: 'Faible',
      competitorPrice: 680000,
      seasonalTrend: 'Baisse'
    },
    {
      id: '4',
      title: 'Excavatrice Komatsu',
      status: 'Stock faible',
      priority: 'medium',
      stock: 1,
      minStock: 2,
      category: 'Équipements lourds',
      supplier: 'Komatsu Maroc',
      lastOrder: '2024-01-12',
      nextDelivery: '2024-01-28',
      value: 580000,
      location: 'Entrepôt Fès',
      dormantDays: 12,
      visibilityRate: 65,
      averageSalesTime: 28,
      clickCount: 22,
      lastContact: '2024-01-18',
      priceReduction: 0,
      premiumBoost: true,
      salesHistory: [620000, 600000, 580000, 560000, 540000],
      marketDemand: 'Élevée',
      competitorPrice: 600000,
      seasonalTrend: 'Hausse'
    },
    {
      id: '5',
      title: 'Camion benne 20T',
      status: 'Disponible',
      priority: 'low',
      stock: 6,
      minStock: 3,
      category: 'Transport',
      supplier: 'Mercedes Maroc',
      lastOrder: '2024-01-08',
      nextDelivery: null,
      value: 280000,
      location: 'Entrepôt Agadir',
      dormantDays: 8,
      visibilityRate: 85,
      averageSalesTime: 15,
      clickCount: 45,
      lastContact: '2024-01-20',
      priceReduction: 0,
      premiumBoost: true,
      salesHistory: [300000, 290000, 285000, 280000, 275000],
      marketDemand: 'Très élevée',
      competitorPrice: 290000,
      seasonalTrend: 'Hausse'
    },
    {
      id: '6',
      title: 'Pelle hydraulique Hitachi',
      status: 'Stock dormant',
      priority: 'high',
      stock: 3,
      minStock: 2,
      category: 'Équipements lourds',
      supplier: 'Hitachi Maroc',
      lastOrder: '2024-01-03',
      nextDelivery: null,
      value: 720000,
      location: 'Entrepôt Tanger',
      dormantDays: 78,
      visibilityRate: 12,
      averageSalesTime: 52,
      clickCount: 2,
      lastContact: '2024-01-05',
      priceReduction: 0,
      premiumBoost: false,
      salesHistory: [800000, 760000, 720000, 680000, 640000],
      marketDemand: 'Moyenne',
      competitorPrice: 750000,
      seasonalTrend: 'Stable'
    },
    {
      id: '7',
      title: 'Chargeur frontal Volvo',
      status: 'Faible visibilité',
      priority: 'medium',
      stock: 2,
      minStock: 2,
      category: 'Équipements lourds',
      supplier: 'Volvo Maroc',
      lastOrder: '2024-01-14',
      nextDelivery: null,
      value: 380000,
      location: 'Entrepôt Meknès',
      dormantDays: 35,
      visibilityRate: 28,
      averageSalesTime: 42,
      clickCount: 6,
      lastContact: '2024-01-16',
      priceReduction: 0,
      premiumBoost: false,
      salesHistory: [420000, 400000, 380000, 360000, 340000],
      marketDemand: 'Moyenne',
      competitorPrice: 400000,
      seasonalTrend: 'Stable'
    }
  ],
  'equipment-availability': [
    { id: '1', title: 'Pelle hydraulique', status: 'Disponible', location: 'Casablanca' },
    { id: '2', title: 'Chargeur frontal', status: 'En location',  location: 'Rabat' },
    { id: '3', title: 'Bulldozer',        status: 'Maintenance',  location: 'Marrakech' }
  ],
  'repair-status': [
    {
      id: '1',
      equipment: 'Pelle CAT 320',
      status: 'En cours',
      priority: 'Haute',
      technician: 'Ahmed Benali',
      startDate: '2024-01-20',
      estimatedCompletion: '2024-01-25',
      actualCompletion: null,
      description: 'Réparation moteur - Problème de surchauffe',
      parts: ['Joint de culasse', 'Thermostat', 'Liquide de refroidissement'],
      cost: 45000,
      location: 'Atelier Casablanca',
      progress: 65,
      urgency: 'Critique',
      notes: 'Attente pièces détachées - Livraison prévue demain',
      photos: ['moteur_avant.jpg', 'moteur_apres.jpg'],
      supplier: 'CAT Maroc',
      supplierPhone: '+212 5 22 34 56 78',
      nextSteps: ['Réception pièces', 'Montage', 'Test moteur', 'Validation']
    },
    {
      id: '2',
      equipment: 'Chargeur JCB 3CX',
      status: 'En attente',
      priority: 'Moyenne',
      technician: 'Mohammed Tazi',
      startDate: '2024-01-18',
      estimatedCompletion: '2024-01-22',
      actualCompletion: null,
      description: 'Réparation système hydraulique',
      parts: ['Pompe hydraulique', 'Filtres', 'Huile hydraulique'],
      cost: 28000,
      location: 'Atelier Rabat',
      progress: 30,
      urgency: 'Normale',
      notes: 'Pièces disponibles - Intervention prévue cet après-midi',
      photos: ['hydraulique_avant.jpg'],
      supplier: 'JCB Maroc',
      supplierPhone: '+212 5 37 21 43 65',
      nextSteps: ['Diagnostic complet', 'Remplacement pompe', 'Test système']
    },
    {
      id: '3',
      equipment: 'Bulldozer D6',
      status: 'Terminé',
      priority: 'Basse',
      technician: 'Hassan El Fassi',
      startDate: '2024-01-15',
      estimatedCompletion: '2024-01-18',
      actualCompletion: '2024-01-17',
      description: 'Révision générale - Changement filtres et huiles',
      parts: ['Filtres à air', 'Filtres à huile', 'Huile moteur', 'Filtres carburant'],
      cost: 12000,
      location: 'Atelier Marrakech',
      progress: 100,
      urgency: 'Normale',
      notes: 'Réparation terminée avec succès - Équipement opérationnel',
      photos: ['revision_complete.jpg'],
      supplier: 'CAT Maroc',
      supplierPhone: '+212 5 24 38 76 54',
      nextSteps: ['Validation client', 'Livraison', 'Documentation']
    },
    {
      id: '4',
      equipment: 'Excavatrice Komatsu',
      status: 'En cours',
      priority: 'Haute',
      technician: 'Youssef Alami',
      startDate: '2024-01-19',
      estimatedCompletion: '2024-01-26',
      actualCompletion: null,
      description: 'Réparation bras hydraulique - Fuite importante',
      parts: ['Cylindre hydraulique', 'Flexibles', 'Joint torique'],
      cost: 35000,
      location: 'Atelier Tanger',
      progress: 45,
      urgency: 'Urgente',
      notes: 'Fuite critique détectée - Intervention d\'urgence',
      photos: ['bras_avant.jpg', 'fuite_detail.jpg'],
      supplier: 'Komatsu Maroc',
      supplierPhone: '+212 5 39 32 18 47',
      nextSteps: ['Remplacement cylindre', 'Test pression', 'Validation étanchéité']
    },
    {
      id: '5',
      equipment: 'Camion benne Volvo',
      status: 'Planifié',
      priority: 'Moyenne',
      technician: 'Karim Bennani',
      startDate: '2024-01-26',
      estimatedCompletion: '2024-01-28',
      actualCompletion: null,
      description: 'Maintenance préventive - Révision complète',
      parts: ['Filtres', 'Huiles', 'Plaquettes frein', 'Courroies'],
      cost: 18000,
      location: 'Atelier Fès',
      progress: 0,
      urgency: 'Normale',
      notes: 'Maintenance planifiée - Équipement disponible',
      photos: [],
      supplier: 'Volvo Maroc',
      supplierPhone: '+212 5 35 67 89 12',
      nextSteps: ['Réception équipement', 'Diagnostic', 'Intervention']
    }
  ],
  'gps-tracking': [
    { id: '1', title: 'Camion 001', status: 'En transit', location: 'Route A1',    eta: '2h' },
    { id: '2', title: 'Camion 002', status: 'Livraison',  location: 'Casablanca', eta: '30min' }
  ],
  'documents': [
    { id: '1', title: 'Facture 2024-001', status: 'En attente', type: 'Facture' },
    { id: '2', title: 'Devis 2024-002',   status: 'Validé',    type: 'Devis' }
  ],
  'stock-alerts': [
    { id: '1', title: 'Pelle CAT 320', status: 'Rupture',      priority: 'high' },
    { id: '2', title: 'Chargeur JCB',  status: 'Stock faible', priority: 'medium' }
  ],
};
